# Uncomment this line to define a global platform for your project
# platform :ios, "6.0"

target "YAPhotoBroswerDemo" do

pod 'SDWebImage', '~> 3.5.1'
pod 'FFCircularProgressView', '~> 0.3'

end

target "YAPhotoBroswerDemoTests" do

end

