# Uncomment this line to define a global platform for your project
# platform :ios, "6.0"

target "YAPhotoBroswerDemo" do

pod 'SDWebImage', '~> 3.5.1'
pod 'MDRadialProgress', '~> 0.4.0'
pod 'MRCircularProgressView', :git => 'https://github.com/candyan/MRCircularProgressView.git', :tag => '0.2.0'

end

target "YAPhotoBroswerDemoTests" do

end

